### ISSUE TITLE
update

### ISSUE THREAD

**Issue by MGTV01** [kelliark/hk-keygen#3]
Hello, dear engineer, 2 new games have been added to Hamster Kombat. Please add them

**Comment by kelliark** [comment]
> Hello, dear engineer, 2 new games have been added to Hamster Kombat. Please add them

added and new option, get 20 keys at once so you don't need to open the bot everyday

**Comment by MGTV01** [comment]
> > Hello, dear engineer, 2 new games have been added to Hamster Kombat. Please add them
> 
> added and new option, get 20 keys at once so you don't need to open the bot everyday

Thank you engineer
